;;; flycheck-vale-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-vale.el

(autoload 'flycheck-vale-setup "flycheck-vale" "\
Convenience function to setup the vale flycheck checker.

This adds the vale checker to the list of flycheck checkers.")
(autoload 'flycheck-vale-toggle-enabled "flycheck-vale" "\
Toggle `flycheck-vale-enabled'." t)
(register-definition-prefixes "flycheck-vale" '("flycheck-vale-"))

;;; End of scraped data

(provide 'flycheck-vale-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-vale-autoloads.el ends here
