;;; sql-clickhouse-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sql-clickhouse.el

(autoload 'sql-clickhouse "sql-clickhouse" "\
Run clickhouse-client by ClickHouse as an inferior process.
Optional argument BUFFER current buffer.

(fn &optional BUFFER)" t)
(register-definition-prefixes "sql-clickhouse" '("sql-clickhouse-"))

;;; End of scraped data

(provide 'sql-clickhouse-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sql-clickhouse-autoloads.el ends here
