;;; flymake-fennel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-fennel.el

(autoload 'flymake-fennel-setup "flymake-fennel" "\
Set up Fennel and Flymake." t)
(register-definition-prefixes "flymake-fennel" '("flymake-fennel-"))

;;; End of scraped data

(provide 'flymake-fennel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-fennel-autoloads.el ends here
