;;; flycheck-julia-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-julia.el

(autoload 'flycheck-julia-setup "flycheck-julia" "\
Setup Flycheck Julia.

Add `flycheck-julia' to `flycheck-checkers'." t)
(register-definition-prefixes "flycheck-julia" '("flycheck-julia-"))

;;; End of scraped data

(provide 'flycheck-julia-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-julia-autoloads.el ends here
