;;; ruff-format-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ruff-format.el

 (autoload 'ruff-format-buffer "ruff-format" nil t)
 (autoload 'ruff-format-region "ruff-format" nil t)
 (autoload 'ruff-format-on-save-mode "ruff-format" nil t)
(register-definition-prefixes "ruff-format" '("ruff-format-command"))

;;; End of scraped data

(provide 'ruff-format-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ruff-format-autoloads.el ends here
