;;; company-ctags-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-ctags.el

(autoload 'company-ctags-debug-info "company-ctags" "\
Print all debug information." t)
(autoload 'company-ctags "company-ctags" "\
Completion backend of for ctags.  Execute COMMAND with ARG and IGNORED.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'company-ctags-replace-backend "company-ctags" "\
Replace `company-etags' with `company-ctags' in BACKENDS.

(fn BACKENDS)")
(autoload 'company-ctags-auto-setup "company-ctags" "\
Set up `company-backends'.")
(register-definition-prefixes "company-ctags" '("company-ctags-"))

;;; End of scraped data

(provide 'company-ctags-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-ctags-autoloads.el ends here
