;;; flycheck-irony-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-irony.el

(autoload 'flycheck-irony-setup "flycheck-irony" "\
Setup Flycheck Irony.

Add `irony' to `flycheck-checkers'." t)
(register-definition-prefixes "flycheck-irony" '("flycheck-irony-"))

;;; End of scraped data

(provide 'flycheck-irony-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-irony-autoloads.el ends here
