;;; go-eldoc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go-eldoc.el

(autoload 'go-eldoc-setup "go-eldoc" "\
Set up eldoc function and enable eldoc-mode." t)
(register-definition-prefixes "go-eldoc" '("go-eldoc-"))

;;; End of scraped data

(provide 'go-eldoc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-eldoc-autoloads.el ends here
